# Generated by Django 4.2.27 on 2026-01-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentchunk'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('document', 'order'), name='unique_chunk_order_per_document'),
        ),
    ]
