# Generated by Django 4.2.27 on 2026-01-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentchunk_unique_chunk_order_per_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='embedded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('embedded', 'Embedded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='text_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
            preserve_default=False,
        ),
    ]
