# Generated by Django 4.2.27 on 2026-01-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documentchunk_embedded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
