# Generated by Django 4.2.27 on 2026-01-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_is_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('owner',), name='unique_active_document_per_owner'),
        ),
    ]
