# Generated by Django 4.2.27 on 2026-06-02 16:46

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_enable_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
