# Generated by Django 4.2.27 on 2026-06-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_documentchunk_embedding_vector_hnsw'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='unique_active_document_per_owner',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_active',
        ),
    ]
