# Generated by Django 4.2.27 on 2026-06-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_remove_document_unique_active_document_per_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='documentation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='documentation_status',
            field=models.CharField(choices=[('none', 'None'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='none', max_length=20),
        ),
    ]
