# Generated by Django 4.2.27 on 2026-06-27 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0017_alter_conversation_project_alter_document_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('vulnerability', 'Vulnerability'), ('architecture', 'Architecture decision'), ('limitation', 'Known limitation'), ('decision', 'User decision')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='El detalle del hallazgo.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('obsolete', 'Obsolete')], default='active', max_length=20)),
                ('fingerprint', models.CharField(db_index=True, help_text='Huella para deduplicar (hash de project+category+archivo+resumen).', max_length=64)),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Prueba: archivo, simbolo, lineas, tool que lo origino.')),
                ('times_seen', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='documents.project')),
                ('source_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories_created', to='documents.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Project memories',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectmemory',
            constraint=models.UniqueConstraint(fields=('project', 'fingerprint'), name='unique_project_memory_fingerprint'),
        ),
    ]
