# Generated by Django 4.2.27 on 2026-07-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_auditrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmemory',
            name='category',
            field=models.CharField(choices=[('bug', 'Bug'), ('vulnerability', 'Vulnerability'), ('architecture', 'Architecture decision'), ('limitation', 'Known limitation'), ('decision', 'User decision'), ('audit_summary', 'Audit summary')], max_length=30),
        ),
    ]
